"""
World Author — one Claude call to dress the Python skeleton with lore.
Also generates rich player backstories with family history.

Python builds the bones (coordinates, populations, roads, factions).
Claude writes the soul (history, religion, culture, names, backstories).
"""
import json
from app.ai.models import call_model


def author_world_lore(world) -> dict:
    """
    One Claude call to generate all world lore from the skeleton.
    Populates: history, religion, intellectual_traditions, economy_info, themes.
    ~$0.10-0.15 per call.
    """
    # Build the skeleton summary for Claude
    skeleton = _build_world_skeleton(world)

    prompt = f"""Here is a fantasy world skeleton generated by the game engine.
Write the lore that makes it feel real and lived-in.

{skeleton}

Write the following as JSON (no markdown, just the JSON object):
{{
    "history": "300-400 words. How this world came to be. Major events in the last 500 years. What wars were fought, what empires rose and fell, what shaped the current political situation. Specific dates, names, turning points.",
    "religion": {{
        "name": "name of the dominant faith",
        "description": "150 words. What people believe. Gods or forces they worship. Temple practices. Is there one faith or many? Are there heretics?",
        "gods": ["list of god/spirit names if polytheistic"]
    }},
    "intellectual_traditions": [
        {{"name": "tradition name", "description": "50 words about this school of thought"}}
    ],
    "economy_info": "150 words. What drives trade across the continent. Key trade goods, trade routes, who controls the wealth. What the common person earns vs what a noble spends.",
    "themes": ["3-5 thematic words that capture the world's mood, e.g. 'decay', 'resilience', 'distrust'"],
    "naming_conventions": "50 words. How people are named in different regions. Patronymics? House names? Regional styles?"
}}

Make the lore CONNECT to the existing factions and conflicts.
If House Thorn and House Oakheart are at war, the history should explain WHY.
If a region is coastal, the economy should reflect fishing and trade.
Everything should feel like it grew organically from the geography and politics."""

    try:
        result = call_model("world_builder",
                           "You are a world-builder for a dark fantasy RPG. Write rich, grounded lore. Return valid JSON only.",
                           prompt, json_mode=True)
        if isinstance(result, dict) and "history" in result:
            return result
    except Exception:
        pass

    return {}


def author_player_backstory(player, world) -> str:
    """
    One Claude call to write a rich ~500-word life story for the player character.
    Includes family going back 2-3 generations, upbringing, education, key events.
    ~$0.05-0.10 per call.
    """
    stats = player.stats
    loc = world.locations.get(player.location)
    loc_name = loc.name if loc else "an unknown town"
    city = world.get_city_for_location(player.location) if player.location else None
    city_name = city.name if city else loc_name

    # Build a brief world context
    world_context = f"World: {world.name or 'unnamed'}. Era: {world.era or 'uncertain times'}."
    if world.factions:
        faction_names = [f.get("name", k) if isinstance(f, dict) else k
                        for k, f in list(world.factions.items())[:3]]
        world_context += f" Major powers: {', '.join(faction_names)}."
    if world.active_conflicts:
        c = world.active_conflicts[0]
        conflict_name = c.get("name", str(c)) if isinstance(c, dict) else str(c)
        world_context += f" Current conflict: {conflict_name}."

    # Stat personality hints
    personality = []
    if stats.strength > 65: personality.append("physically strong")
    if stats.intelligence > 65: personality.append("sharp-minded")
    if stats.charisma > 65: personality.append("naturally charming")
    if stats.courage > 65: personality.append("brave, perhaps recklessly so")
    if stats.empathy > 65: personality.append("deeply empathetic")
    if stats.ambition > 65: personality.append("driven by ambition")
    if stats.depth > 65: personality.append("thoughtful, given to reflection")
    if stats.honesty < 30: personality.append("comfortable with deception")
    if stats.loyalty > 70: personality.append("fiercely loyal")
    if stats.creativity > 65: personality.append("creative and unconventional")
    personality_str = ", ".join(personality) if personality else "unremarkable in most ways"

    prompt = f"""Write a 500-word life story for this RPG player character.

CHARACTER:
Name: {player.name}
Starting location: {loc_name} in {city_name}
Weapon: {player.weapon}, Armor: {player.armor}
Coins: {player.coins}
Personality from stats: {personality_str}

WORLD CONTEXT:
{world_context}

REQUIREMENTS:
- Social class and upbringing (match their starting wealth: {player.coins} coins = {'comfortable' if player.coins > 80 else 'modest' if player.coins > 40 else 'poor'})
- Parents: names, occupations, personalities. Are they alive? What's the relationship like?
- Grandparents: brief mention — who they were, what they did
- Siblings: 0-3, with names and one-line descriptions. Not all need to be close.
- Education or training: what did they learn? From whom?
- 1-2 key events that shaped who they are today
- Why they're HERE, in {city_name}, right now. What brought them to this place?
- What they want: not a quest, but a feeling. Direction. Something unresolved.

STYLE:
- Third person, past tense. Literary but accessible.
- Should feel like the first page of a novel, not a character sheet.
- Ground it in physical detail — what the family home looked like, what their mother's hands looked like, the smell of their father's workshop.
- Don't make them special. Don't make them chosen. They're a person with a history, arriving somewhere new."""

    try:
        result = call_model("character_author",
                           "You write rich, grounded character backstories for a dark fantasy RPG. No cliches, no chosen ones. Real people with real histories.",
                           prompt)
        if result and len(result) > 100:
            return result
    except Exception:
        pass

    return player.backstory  # fall back to the archetype template


def apply_world_lore(world, lore: dict):
    """Apply the authored lore back to the world object."""
    if not lore:
        return

    if "history" in lore:
        world.history = lore["history"] if isinstance(lore["history"], dict) else {"summary": lore["history"]}

    if "religion" in lore:
        world.religion = lore["religion"] if isinstance(lore["religion"], dict) else {"description": lore["religion"]}

    if "intellectual_traditions" in lore:
        world.intellectual_traditions = lore["intellectual_traditions"]

    if "economy_info" in lore:
        world.economy_info = lore["economy_info"] if isinstance(lore["economy_info"], dict) else {"summary": lore["economy_info"]}

    if "themes" in lore:
        world.themes = lore["themes"]

    if "naming_conventions" in lore:
        world.naming_conventions = lore["naming_conventions"]


def _build_world_skeleton(world) -> str:
    """Format the world skeleton for Claude to read."""
    parts = []

    parts.append(f"World name: {world.name or '(needs a name)'}")
    parts.append(f"Era: {world.era or '(needs an era name)'}")
    parts.append(f"Tone: {world.tone or 'grim but not hopeless'}")

    # Regions
    regions = [l for l in world.locations.values() if l.type == "region"]
    if regions:
        parts.append(f"\nREGIONS ({len(regions)}):")
        for r in regions:
            cities = [world.locations[c] for c in r.children_ids
                     if c in world.locations and world.locations[c].type == "city"]
            city_list = ", ".join(f"{c.name} (pop {c.population:,})" for c in cities[:5])
            parts.append(f"  - {r.name} ({r.terrain or 'mixed'}, pop {r.population:,})")
            parts.append(f"    Cities: {city_list}")

    # Factions
    if world.factions:
        parts.append(f"\nFACTIONS ({len(world.factions)}):")
        for fid, f in world.factions.items():
            if isinstance(f, dict):
                parts.append(f"  - {f.get('name', fid)}: {f.get('government', '?')}, "
                           f"ruler {f.get('title', '')} {f.get('ruler', '?')} (age {f.get('ruler_age', '?')}), "
                           f"strength: {f.get('strength', '?')}")
                if f.get('lineage'):
                    parts.append(f"    Lineage: {', '.join(f['lineage'])}")

    # Conflicts
    if world.active_conflicts:
        parts.append(f"\nACTIVE CONFLICTS:")
        for c in world.active_conflicts:
            if isinstance(c, dict):
                parts.append(f"  - {c.get('name', '?')}: {c.get('current_status', '?')}")

    return "\n".join(parts)
